version: "3.7"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    environment:
      APP_NAME: "watertracker"
      SERVICE_NAME: "watertracker"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on: 
      - flask
    restart: unless-stopped
    networks: 
      - frontend
    ports:
      - "80:80"
    # deploy:

  flask:
    build: ./flask
    image: flask
    container_name: flask
    # secrets:
    #   - sqlalchemy_uri
    environment: 
      FLASK_ENV: "development"
      # SQLALCHEMY_DATABASE_URI: /run/secrets/sqlalchemy_uri.txt
    networks: 
      - frontend
    volumes:
      - ./flask:/var/www/flask
    
    # deploy:

volumes:
  appdata:
    driver: local
  nginxdata:
    driver: local

networks:
  frontend:
    driver: bridge

# secrets:
#   sqlalchemy_uri: 
#     file: ./sqlalchemy_uri.txt
