"""empty message

Revision ID: dc26e9659724
Revises: bd5916106e40
Create Date: 2021-02-05 22:39:33.204244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc26e9659724'
down_revision = 'bd5916106e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access', sa.Enum('USER', 'ADMIN', name='access'), nullable=False))
    op.add_column('users', sa.Column('daily_goal_amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'daily_goal_amount')
    op.drop_column('users', 'access')
    # ### end Alembic commands ###
